### PR TITLE
Update name

### PR DESCRIPTION
**Pull request by sonnyp**

### CODE REVIEW

**Review by shiftkey — APPROVED** [review]

**Comment by Lunarequest** [comment]
This doesn't work, once its merged into main it will fail to publish. We need to resubmit the app for it to work

**Comment by sonnyp** [comment]
>  once its merged into main it will fail to publish

why?

**Comment by Lunarequest** [comment]
> > once its merged into main it will fail to publish
> 
> why?

Buildbot doesn't know which repo it was published from.

**Comment by sonnyp** [comment]
I don't understand but I'm afraid you're mistaken. 



This is only changing the display name to show "Github Desktop" instead of "Github-desktop" here

Screenshot from 2021-12-20 14-06-13



In case that's what you had in mind, this has nothing to do with https://github.com/flathub/io.github.shiftey.Desktop/issues/12

**Comment by Lunarequest** [comment]
Ah me had I got confused what this proposed

**Comment by sonnyp** [comment]
Thank you both for making this popular app available on Linux/Flathub :100:

**Pull request merged**
